#!/bin/bash

cd /usr/src/tm-libfuse

make uninstall
make distclean

# Remove dirs that distclean misses
rm -rf /usr/src/tm-libfuse/include
rm -rf /usr/src/tm-libfuse/example
rm -rf /usr/src/tm-libfuse/lib
rm -rf /usr/src/tm-libfuse/util
rm -rf /usr/src/tm-libfuse/doc
rm -rf /usr/src/tm-libfuse/m4
rm -rf /usr/src/tm-libfuse/autom4te.cache

# Remove files that distclean misses
rm -f /usr/src/tm-libfuse/aclocal.m4
rm -f /usr/src/tm-libfuse/compile
rm -f /usr/src/tm-libfuse/config.sub
rm -f /usr/src/tm-libfuse/depcomp
rm -f /usr/src/tm-libfuse/install-sh
rm -f /usr/src/tm-libfuse/m4
rm -f /usr/src/tm-libfuse/missing
rm -f /usr/src/tm-libfuse/autom4te.cache
rm -f /usr/src/tm-libfuse/config.guess
rm -f /usr/src/tm-libfuse/configure
rm -f /usr/src/tm-libfuse/INSTALL
rm -f /usr/src/tm-libfuse/ltmain.sh
rm -f /usr/src/tm-libfuse/Makefile.in

exit 0
